name: 522-milestone2
channels:
  - conda-forge
dependencies:
  - pandas=2.2.2
  - python=3.11.9
  - numpy=1.26.4
  - pandera=0.18.0
  - scikit-learn=1.5.0
prefix: /Users/tseeugene/miniforge3/envs/522-milestone2
